name: riverpod_request_helpers
description: A helper for creating providers with riverpod to do async operations.
version: 0.0.3
repository: https://github.com/Fidev-io/riverpod_request_helpers

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^1.0.4
  freezed_annotation: ^2.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  build_runner: any
